# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQLUZ9_-ePCInbtxkcJJYoBY30pUCirj
"""

# Создание класса Database для работы с базой данных
class Database:
    def __init__(self):
        self.data = []

    def insert(self, record):
        """Вставка записи в базу данных"""
        self.data.append(record)

    def update(self, index, new_record):
        """Обновление записи по индексу"""
        if index < len(self.data):
            self.data[index] = new_record
        else:
            raise IndexError("Index out of range")

    def delete(self, index):
        """Удаление записи по индексу"""
        if index < len(self.data):
            del self.data[index]
        else:
            raise IndexError("Index out of range")

    def search(self, condition):
        """Поиск записи по условию"""
        return [record for record in self.data if condition(record)]

    def __str__(self):
        return str(self.data)


# Импортируем библиотеку для тестирования
import unittest

# Класс для автоматического тестирования
class TestDatabase(unittest.TestCase):

    def setUp(self):
        """Настройка тестов"""
        self.db = Database()

    def test_insert(self):
        self.db.insert("Record 1")
        self.assertEqual(self.db.data, ["Record 1"])

    def test_update(self):
        self.db.insert("Record 1")
        self.db.update(0, "Updated Record")
        self.assertEqual(self.db.data, ["Updated Record"])

    def test_delete(self):
        self.db.insert("Record 1")
        self.db.delete(0)
        self.assertEqual(self.db.data, [])

    def test_search(self):
        self.db.insert("Record 1")
        self.db.insert("Record 2")
        result = self.db.search(lambda x: "1" in x)
        self.assertEqual(result, ["Record 1"])

    def test_update_out_of_range(self):
        with self.assertRaises(IndexError):
            self.db.update(0, "New Record")

    def test_delete_out_of_range(self):
        with self.assertRaises(IndexError):
            self.db.delete(0)

# Выполнение тестов
def run_tests():
    unittest.main(argv=[''], verbosity=2, exit=False)


# Внесение ошибки в программу (пример изменения кода)
class DatabaseWithBug(Database):
    def insert(self, record):
        """Вставка записи с ошибкой (например, записывается неверная строка)"""
        self.data.append("Wrong Record")


# Внесение исправлений
class DatabaseFixed(Database):
    def insert(self, record):
        """Исправленная версия метода"""
        self.data.append(record)


# Профилирование программы
import cProfile

def profile_db_operations():
    db = Database()
    db.insert("Test Record")
    db.update(0, "Updated Test Record")
    db.delete(0)

# Запуск тестов
print("Запуск тестов с правильной реализацией Database:")
run_tests()

# Запуск тестов с ошибочной реализацией (DatabaseWithBug)
print("\nЗапуск тестов с ошибочной реализацией DatabaseWithBug:")
db_with_bug = DatabaseWithBug()
db_with_bug.insert("Test Record")
run_tests()

# Исправление ошибки и повторный запуск тестов
print("\nЗапуск тестов с исправленной реализацией DatabaseFixed:")
db_fixed = DatabaseFixed()
db_fixed.insert("Test Record")
run_tests()

# Профилирование операций с базой данных
print("\nПрофилирование базы данных:")
cProfile.run('profile_db_operations()')